name: Pull Request CI
on: pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # --- Install with caching
      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install packages
        run: pnpm install

      - name: Check formatting
        id: check
        run: pnpm format:check

      - name: Fix documentation formatting
        if: ${{ failure() && steps.check.conclusion == 'failure' }}
        id: fix-format
        run: pnpm format:fix
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "${GITHUB_ACTOR}"
          git add --all
          git commit -m "Apply format fixed on $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} master:format-autofix/${{ github.head_ref }}

      - name: Open a formatting PR
        uses: rematocorp/open-pull-request-action@v1
        id: open-format-pr
        if: ${{ steps.fix-format.conclusion == 'success' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: format-autofix/${{ github.head_ref }}
          to-branch: ${{ github.actor }}:${{ github.head_ref }}
          repository-owner: "0x009922"
          repository: test-format-on-pr
